### PR TITLE
[AWS] Update default image, fix spark envvars, set new version

### PR DESCRIPTION
**Pull request by psmadbec**
Simpler than you would think.

(1) passes through the aws change to allow spark env vars to be set again
(2) Removes any specification of emr versions such that everything is now upgraded to using 6.7
(3) renames the cluster bootstrap in bioindex

That's it. There will likely be some edges that need to be smoothed out, but vision private portal and the release should help find and correct those, plus they fail fast when it happens, and they've always been quite easy to revolve. Finally, the old 5.30 was crapping out 80% of the time anyways, so this just gets the show on the road.

### CODE REVIEW

**Comment by psmadbec** [comment]
Screenshot 2024-01-19 at 12 16 20 PM
Screenshot 2024-01-19 at 12 03 13 PM
Screenshot 2024-01-19 at 12 03 07 PM

**Comment by psmadbec** [comment]
The images show basically that indeed, the text bioindex job I ran updgraded the version, and I was able to see the env vars set in the configuration and they printed off inside of the job as well.

**Review by sagehen03 — APPROVED** [review]
I need to get to know this code better before opining too much, but it seems repetitive to have boostrapScripts and possibly other information specified in each stage.  Couldn't we define a default value and then let those stages that want to override do so?

**Comment by psmadbec** [comment]
There are defaults set in dig-aws under ClusterDef: 
```
final case class ClusterDef(
    name: String,
    amiId: Option[AmiId] = None, //AmiId.amazonLinux_2018_3,
    releaseLabel: ReleaseLabel = ReleaseLabel.emrDefault,
    instances: Int = 3,
    masterInstanceType: Strategy = Strategy.default,
    slaveInstanceType: Strategy = Strategy.default,
    masterVolumeSizeInGB: Int = 32,
    slaveVolumeSizeInGB: Int = 32,
    applications: Seq[ApplicationName] = ClusterDef.Defaults.applications,
    applicationConfigurations: Seq[Configuration] = Seq.empty,
    bootstrapScripts: Seq[BootstrapScript] = Seq.empty,
    bootstrapSteps: Seq[Job.Step] = Seq.empty,
    visibleToAllUsers: Boolean = true,
    stepConcurrency: Integer = 1,
    masterEbsVolumeType: EbsVolumeType = ClusterDef.Defaults.masterEbsVolumeType,
    slaveEbsVolumeType: EbsVolumeType = ClusterDef.Defaults.slaveEbsVolumeType,
) {
```
e.g. you by default use 3 m.2xlarge clusters.

There are some stages where nothing is added (some of the very very small bioindex one specifically). The config defaults are then modified (in Stage.scala):

```
/** The cluster definition to instantiate for this processor. This is a
    * very basic configuration that should work for a good number of jobs.
    */
  def cluster: ClusterDef = {
    val applicationConfigurations = Seq(
      new Spark.Env().usePython3(),
      new Spark.Config().maximizeResourceAllocation()
    )

    context.config match {
      case Some(config) => {
        import config.aws.emr

        ClusterDef(
          name = getName,
          applicationConfigurations = applicationConfigurations,
          masterEbsVolumeType = emr.masterEbsVolumeType,
          slaveEbsVolumeType = emr.slaveEbsVolumeType
        )
      }
```

later is does add a common-bootstrap that everything uses:
```
// add a bootstrap step to the cluster for installing things needed by the aggregator
      val clusterCommon = {
        val common  = new BootstrapScript(resourceUri("common-bootstrap.sh"))
        val scripts = cluster.bootstrapScripts :+ common

        cluster.copy(bootstrapScripts = scripts)
      }
      
```

but it doesn't specify much:
```
#!/bin/bash -xe

sudo pip3 install boto3
sudo pip3 install pymysql
```

And yeah, at some point that should be expanded to include installing zstd and a few other things which are sometimes the only thing we end up specifying in bootstraps and take 0 seconds to install and no space. But for the most part each job basically has its own "Docker" configuration in that scipy and numpy take a while to install so you only want to install them when needed, and a lot of the methods also include s3 data which needs to be downloaded prior to a run, very similar to making minimal docker configs for every method we run.

That being said I'm pretty sure the cluster-bootstrap for the bioindex is nonsense at this point and probably we could add matplotlib and zstd to the common-bootstrap and everything will work without overriding the bootstrap there. Which would be good to know going forward with the mini-BI and moving things to docker/batch maybe. But that is for another day.

**Pull request merged**
